# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0aa098b86df285c3637bffbc97d34e1c"
name = "vgroup_swapnil_vhantale"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_draft_orders,read_inventory,read_locations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"
